# Generated by Django 3.0.3 on 2020-08-07 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('miner', '0002_auto_20200806_2254'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tweet',
        ),
        migrations.DeleteModel(
            name='Tweeter',
        ),
    ]
